### ISSUE TITLE
AX_ARIA_10: Incorrect reporting due to incomplete constants definition

### ISSUE THREAD

**Issue by AutoSponge** [GoogleChrome/accessibility-developer-tools#330] opened 2016-12-29 18:25 UTC
```html
[Severe] This element has an unsupported ARIA attribute (1)
See AX_ARIA_10 for more information.
<div role=​"tablist" aria-multiselectable=​"true">​
<div>​…​</div>​
</div>​
```

https://www.w3.org/TR/wai-aria/roles#tablist tablist role constant should inculde `aria-multiselectable` which would probably make this test pass.

relevant code: https://github.com/GoogleChrome/accessibility-developer-tools/blob/b5fd54a6629125b582d10f7b183c7a23151d0894/src/js/Constants.js#L417

NOTE: I tried to build this project and issue the PR myself, but I'm getting an error `ERROR - variable goog is undeclared` and I didn't care to figure out why. Something about a symlink folder and the closure compiler but no docs, no instructions, etc. means I'm not spending time on it.

**Comment by ricksbrown** [comment] 2016-12-30 03:07
Thanks for reporting.
Duplicate of #289

**Closed by ricksbrown** 2016-12-30 03:07 UTC
