### ISSUE TITLE
"This element has an unsuported ARIA attribute" 

### ISSUE THREAD

**Issue by linuslagerhjelm** [GoogleChrome/accessibility-developer-tools#225] opened 2015-08-13 10:39 UTC
I get this error when an input tag of type text has an "aria-required='true'". I've tracked this down and it occurs because role="textbox" is not explicitly set. However, according to the W3 recommendation, this role gets implicitly set and is "not recommended" to declare explicitly.

**Comment by stevefaulkner** [comment] 2015-08-13 10:46
correct, no need to set a role value for a native HTML element that supports the use of the native version of the state/property

**Comment by linuslagerhjelm** [comment] 2015-08-13 10:50
But when left out, the tool will generate an error. Wouldn't that be a bug in the tool? And would best practices be to just ignore the error?

**Comment by stevefaulkner** [comment] 2015-08-13 10:58
suggest tool needs to be fixed

**Comment by RickSBrown** [comment] 2015-08-13 11:26
@linuslagerhjelm Thanks for reporting this, it is definitely a bug in the tool
@stevefaulkner thanks for comments :smile:

**Comment by craigfrancis** [comment] 2015-08-14 09:06
Just to add, this also happens with other elements as well, e.g.

    <th scope="col" aria-sort="ascending">

---

And not sure if this is quite right, but also:

    <abbr title="Required" aria-label="Required">*</abbr>

Where the design of the form uses an asterisk to show which fields are required (the input fields also add the required attribute). Unfortunately the designer insists on not having a key to say what it means (on the basis that "everyone knows what it means, so it clutters the interface"), where aria-labelledby would be better. That said, this is still redundant with the title attribute.

**Comment by RickSBrown** [comment] 2015-08-14 09:55
This one: `<abbr title="Required" aria-label="Required">*</abbr>` is a duplicate of #178 and has already been fixed (but not deployed as part of a release yet) in PR #195 

The other one: `<th scope="col" aria-sort="ascending">` hmmm. I think what's happened is the draft W3C document we based these rules on has gone through a few more iterations and I need to revisit the entire mapping of HTML elements to implicit ARIA roles.

**Comment by craigfrancis** [comment] 2015-08-14 10:09
Thanks Rick, I really appreciate this tool.

And yes, aria-sort has been changed a few times.

I'm still not completely sure I'm using aria-sort correctly, as I'm not using JS to change the order, instead using a simple link in the `<th>` (the tables represent many thousands of records, using pagination, so JS won't be able to handle this without server support).

**Comment by RickSBrown** [comment] 2015-08-14 10:18
Craig - a great place to discuss specific a11y related issues with other developers and major league a11y experts is here: https://gitter.im/w3c/a11ySlackers

Note that it is mainly populated during US working hours and on the weekend it's crickets, tumbleweed etc. There are some on European timezones, some very notable ones actually so it's always worth a shot.

**Comment by stevefaulkner** [comment] 2015-08-14 10:22
I think its fine to use aria-sort on static headers, as per spec it does not say otherwise:
http://www.w3.org/TR/wai-aria-1.1/#aria-sort

**Comment by ricksbrown** [comment] 2015-09-06 05:26
Fixed in release v2.9.0

**Closed by ricksbrown** 2015-09-06 05:26 UTC
Labels: bug
