### ISSUE TITLE
aria-multiselectable=true reported as invalid on element with role=tablist

### ISSUE THREAD

**Issue by gabrielps** [GoogleChrome/accessibility-developer-tools#336] opened 2017-02-09 12:44 UTC
Tested on 
Chrome 49.0.2623.110
Accessibility Developer Tools 2.10.9

```
[Severe] This element has an unsupported ARIA attribute (1)
See AX_ARIA_10 for more information.
<div id=​"accordion" class=​"panel-group " role=​"tablist" aria-multiselectable=​"true">​
[...]
```

[AX_ARIA_10](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_aria_10) says that "Many ARIA attributes (states and properties) can only be used on elements with particular roles". According to [W3](https://www.w3.org/TR/wai-aria/states_and_properties#aria-multiselectable): aria-multiselectable is used in roles: grid, listbox, **tablist**, tree.

Cheers, and thanks for this cool software.

**Comment by ricksbrown** [comment] 2017-02-09 19:34
Thanks.
Duplicate of #289

**Closed by ricksbrown** 2017-02-09 19:34 UTC
