### ISSUE TITLE
Error evaluating site santander.com.br

### ISSUE THREAD

**Issue by davidhsv** [GoogleChrome/accessibility-developer-tools#149] opened 2015-05-01 01:11 UTC
How to replicate: console > phantomjs audit.js http://santander.com.br
---------------------------
TypeError: undefined is not a constructor (evaluating 'op.onshow(this.op)')

  http://www.santander.com.br/document/wps/std-browser-update.js:270 in $buo
*** Begin accessibility audit results ***
An accessibility audit found 
*** End accessibility audit results ***

**Comment by RickSBrown** [comment] 2015-05-02 00:30
@davidhsv Thanks for raising this issue however it has nothing to do with the accessibility-developer-tools codebase in any way - it's actually a problem with the code in http://www.santander.com.br/document/wps/std-browser-update.js which doesn't play nice in PhantomJS.

If you wanted to raise this anywhere then the PhantomJS project would be the place, however my guess is the problem is most likely in the application JS itself, not PhantomJS.

To prove this I ran the following test:
Step 1: Create a file called `test.js` with the following code more or less copied verbatim from [here](http://phantomjs.org/quick-start.html):
```
var page = require('webpage').create();
page.open('http://santander.com.br', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});
```
Step 2: Run the file in phantomjs like so: `phantomjs test.js`
Step 3: Observe the exact same problem:
```
TypeError: 'undefined' is not a function (evaluating 'op.onshow(this.op)')
  http://www.santander.com.br/document/wps/std-browser-update.js:270
  http://www.santander.com.br/document/wps/std-browser-update.js:275
Status: success
```

Since the issue occurs when the accessibility-developer-tools is not loaded this test proves that it is not related to accessibility-developer-tools code. Therefore I am closing this issue.

**Closed by RickSBrown** 2015-05-02 00:30 UTC

**Comment by davidhsv** [comment] 2015-05-02 05:11
Thanks Rick for the answer !

I got futher into the problem and I found that the problem is not about the javascript error indeed, it's the iframe thats is not getting scrapped in the run method.

Please take a look at my Pull Request -> https://github.com/GoogleChrome/accessibility-developer-tools/pull/150

Regards,
David Vieira
